# Generated by Django 6.0.3 on 2026-07-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_program_student_role_and_school_id_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
