# Generated by Django 6.0.3 on 2026-04-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendancesession_late_threshold_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='check_in_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='check_in_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='late_threshold_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='check_out_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='check_out_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='session_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
