# Generated by Django 6.0.3 on 2026-07-14 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_program_section_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='attendance.section'),
        ),
        migrations.AddField(
            model_name='attendanceschedule',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, related_name='schedule_audiences', to='attendance.department'),
        ),
        migrations.AddField(
            model_name='attendanceschedule',
            name='allowed_programs',
            field=models.ManyToManyField(blank=True, related_name='schedule_audiences', to='attendance.program'),
        ),
        migrations.AddField(
            model_name='attendanceschedule',
            name='allowed_roles',
            field=models.CharField(default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='attendanceschedule',
            name='allowed_sections',
            field=models.ManyToManyField(blank=True, related_name='schedule_audiences', to='attendance.section'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, related_name='session_audiences', to='attendance.department'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='allowed_programs',
            field=models.ManyToManyField(blank=True, related_name='session_audiences', to='attendance.program'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='allowed_roles',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='allowed_sections',
            field=models.ManyToManyField(blank=True, related_name='session_audiences', to='attendance.section'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
